### ISSUE TITLE
It does not work in node v4.0

### ISSUE THREAD

**Issue by buryndin** [meredian/jsonsem#2]
Node-v8-clone does not compile on node v4.0. Probably should be replaced by another implementation. For example, like http://stackoverflow.com/questions/4459928/how-to-deep-clone-in-javascript

**Comment by meredian** [comment]
That seems more an issue for `node-clone` itself. I opened an issue: https://github.com/AlexeyKupershtokh/node-v8-clone/issues/14

However, due to new 4.x features from ES6 maybe I'll refactor this code in scope of couple of month. How do you think, should the module be backwards-compatible with older node versions in this case?

**Comment by buryndin** [comment]
Thank you for such a quick reply! To ensure backward compatibility - a good idea, of course. However, ES6 has a number of significant improvements, so compatibility may be sacrificed.

**Comment by meredian** [comment]
Ok, removed usage of `node-v8-clone` in 2de44a07b, now compatible with 4.x
